#pragma once
#include <vector>

namespace ImagePacker
{
    struct ImageInformation_t
    {
        // User provided:
        int     width;
        int     height;
        void*   userdata;

        // Generated by program
        int x = 0, y = 0;

        ImageInformation_t(int w, int h, void* d) : width(w), height(h), userdata(d) {}
    };

    using ImageInformationList = std::vector<ImageInformation_t>;

    // Returns the image size, or 0 if generation failed. Defaults to 64x64
    int GeneratePackedList(ImageInformationList& list);
    int GeneratePackedList(ImageInformationList& list, int imageStartSizeHint);
}